Engine:
  Local:
    Bundles:
      # - https://github.com/agnosticeng/agnostic-clickhouse-udf/releases/download/v0.0.12/agnostic-clickhouse-udf_0.0.12_darwin_arm64.tar.gz
      - file://../agnostic-clickhouse-udf/tmp/bundle.tar.gz
      - file://../icepq/tmp/bundle.tar.gz#disable-cache=true
    Settings:
      allow_experimental_dynamic_type: 1
      enable_named_columns_in_function_tuple: 1
      max_execution_time: 3600
      send_logs_level: warning
      enable_json_type: 1
      enable_dynamic_type: 1
      schema_inference_make_columns_nullable: auto
      max_bytes_before_external_sort: 4294967296
      output_format_parquet_string_as_string: 0
      output_format_parquet_use_custom_encoder: 1
      output_format_parquet_write_page_index: 1
      output_format_parquet_write_bloom_filter: 1
      output_format_parquet_parallel_encoding: 0

Init:
  Queries:
    - init_start.sql#ignore-failure=true
    
Source:
  Query: source.sql
  StopOnEmpty: true

Processors:
  - Debug: {}
  - Map: 
      Queries:
        - create_buffer.sql
    Workers: 4
  - Seq: {}
  - Batch:
      Queries:
        - merge_buffers.sql
      SizeQuery: buffers_size.sql
      MaxWait: 120s
      MaxSize: 50000000
  - Debug: {}
  - Map: 
      Queries:
        - write_parquet_file.sql
        - append_to_table.sql
        - delete_buffers.sql